### ISSUE TITLE
Providing SDE docker images from CI

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [p4lang/open-p4studio#103]
Hi all,

I created a docker image with a prebuilt version of open-p4studio. This allows me to do two things:

1. Building and verifying my data plane build in the CI, for example, like [here](https://github.com/uni-tue-kn/P4TG/actions/runs/15703088083/job/44242418444)
2. Compiling a P4 project locally for the Tofino model without the need for compiling p4studio. I am using a docker-compose file like the following for example:

```yaml
version: '3.8'
services:
  p4compiler:
    image: fihle/open-p4studio:9.13.4
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sudo -E /open-p4studio/install/bin/bf-p4c -D__TARGET_TOFINO__=1 --target tofino -g --arch tna -o /opt/p4program p4program.p4
    environment:
      SDE: /open-p4studio
      SDE_INSTALL: /open-p4studio/install
```

It would be nice to have such a docker image being automatically built and provided by the official repository.

I automated the docker image build process in my fork of this repository. It includes a [Dockerfile](https://github.com/n1tr0-5urf3r/open-p4studio/blob/main/Dockerfile) for building a container containing p4studio, a [CI step](https://github.com/n1tr0-5urf3r/open-p4studio/blob/main/.github/workflows/docker-image-sde.yml) to push an image to a container registry (Docker Hub in my case), and a lightweight [profile](https://github.com/n1tr0-5urf3r/open-p4studio/blob/main/p4studio/profiles/docker.yaml).

To push the image to Docker Hub, the secrets `DOCKER_USERNAME` and `DOCKER_PASSWORD` need to be configured for the repository.
Further, my CI file might be a bit redundant with the existing test steps, so there is room for optimization.
Running the model inside the container may also be possible, but I haven't checked that yet since I am not using the model.

If such a feature is appreciated and/or desired, I'd be happy to open a PR!

Best,
Fabian
